
name: build-tests-image

on:
  push:
    branches: [ "main" ]
    paths:
      - "tests/**"
      - "Dockerfile.playwright"
      - ".github/workflows/upload-tests-image.yaml"

permissions:
  contents: read
  packages: write

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set lowercase image owner
        run: |
          echo "IMAGE_OWNER=$(echo "${{ github.repository_owner }}" | tr '[:upper:]' '[:lower:]')" >> "$GITHUB_ENV"

      - name: Log in to GHCR
        run: |
          echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u "${{ github.actor }}" --password-stdin

      - name: Build tests image
        run: |
          docker build -t ghcr.io/${{ env.IMAGE_OWNER }}/dummy-app:${{ github.sha }} \
            -f Dockerfile.playwright .

      - name: Push
        run: |
          docker push ghcr.io/${{ env.IMAGE_OWNER }}/dummy-app:${{ github.sha }}