
name: build-tests-image

on:
  push:
    branches: [ "main" ]
    paths:
      - "tests/**"
      - "Dockerfile.playwright"   # if you keep Dockerfile at root
      - ".github/workflows/upload-tests-image.yml"

permissions:
  contents: read
  packages: write

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Log in to GHCR
        run: |
          echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u "${{ github.actor }}" --password-stdin

      - name: Build tests image
        run: |
          docker build -t ghcr.io/${{ github.repository_owner }}/e2e-tests:${{ github.sha }} \
            -f tests/Dockerfile tests/

      - name: Push
        run: |
          docker push ghcr.io/${{ github.repository_owner }}/e2e-tests:${{ github.sha }}